import Footer from '@/components/Footer'
import './globals.css'
//
import { Source_Sans_Pro } from 'next/font/google'
import Navbar from '@/components/Navbar'

const poppins = Source_Sans_Pro({ weight: '400' })

export const metadata = {
    title: 'Starlyn Thrilling Adventures',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true} className={poppins.className}>
                <>
                    <Navbar />
                    <>
                        {children}
                    </>
                    <Footer />
                </>
            </body>
        </html >
    )
}
